import pandas as pd
import numpy as np

def generate_mock_ledger(num_records=5000):
    """Generates a realistic, messy transaction ledger."""
    np.random.seed(42)
    
    # Simulating a company with 200 total clients, but a few massive whales
    client_ids = [f"Client_{i}" for i in range(1, 201)]
    
    # Pareto distribution to simulate 80/20 rule reality
    transaction_sizes = np.random.pareto(a=1.5, size=num_records) * 1000 
    clients = np.random.choice(client_ids, size=num_records, p=np.random.dirichlet(np.ones(200)))
    
    df = pd.DataFrame({
        'Transaction_ID': range(10000, 10000 + num_records),
        'Client_ID': clients,
        'Revenue_USD': transaction_sizes
    })
    
    return df

def audit_concentration_risk(df):
    """Audits the ledger for revenue concentration and HHI."""
    print("--- AUTOMATED CDD: REVENUE INTEGRITY AUDIT ---")
    
    # Aggregate revenue by client
    client_rev = df.groupby('Client_ID')['Revenue_USD'].sum().sort_values(ascending=False)
    total_revenue = client_rev.sum()
    
    # 1. Top Client Exposure
    top_5_clients = client_rev.head(5)
    top_5_pct = (top_5_clients.sum() / total_revenue) * 100
    print(f"\n[!] Top 5 Clients account for {top_5_pct:.2f}% of Total Revenue.")
    
    # 2. The 80/20 Rule Check
    cumulative_rev = client_rev.cumsum() / total_revenue
    clients_making_80_pct = (cumulative_rev <= 0.80).sum()
    total_clients = len(client_rev)
    pct_clients_making_80 = (clients_making_80_pct / total_clients) * 100
    print(f"[!] 80% of revenue is generated by just {clients_making_80_pct} clients ({pct_clients_making_80:.2f}% of customer base).")
    
    # 3. Herfindahl-Hirschman Index (HHI)
    # HHI > 2500 indicates highly concentrated (monopoly-like risk on the buyer side)
    market_shares = (client_rev / total_revenue) * 100
    hhi = (market_shares ** 2).sum()
    
    risk_level = "HIGH (Deal Breaker?)" if hhi > 2500 else "MODERATE" if hhi > 1500 else "LOW (Diversified)"
    print(f"[!] Customer HHI Score: {hhi:.2f} -> Risk Level: {risk_level}")

if __name__ == "__main__":
    # Run the engine
    ledger_df = generate_mock_ledger()
    audit_concentration_risk(ledger_df)